### ISSUE TITLE
Document new CRD

### ISSUE THREAD

**Issue by fabolive** [iter8-tools/docs#79]

**Comment by kalantar** [comment]
CRD v1alpah2 is https://app.zenhub.com/workspaces/iter8-5e8231e5559a7027a3e7a971/issues/iter8-tools/iter8-controller/97

**Comment by kalantar** [comment]
Questions:

@sriumcp @kimikowang As I attempted to document the new CRD, some questions are arising. I will document them here and tag you for your input.  Much appreciated.

**Comment by kalantar** [comment]
@kimikowang @sriumcp 

Suppose we start with:
````yaml
service:
    baseline: v1
    candidates: [ "v2" ]
trafficControl:
    percentage: 50
````
Suppose the user patches the experiment with:
 ```yaml
manualOverride:
    action: terminate
    trafficSplit:
        v1: 50
        v2: 50
```
What will the final percentages for `v1` and `v2` be? _50-50_ or _75-25_ ? That is, does `manaulOverride.trafficSplit` apply only to `trafficSplit.percentage` or to the whole traffic pattern?
