### ISSUE TITLE
Experiment YAML file for scenario 1 deviated from the tutorial instructions

### ISSUE THREAD

**Issue by fabolive** [iter8-tools/docs#83]
In particular, I see this:

```yaml
apiVersion: iter8.tools/v1alpha1
kind: Experiment
metadata:
  name: reviews-v3-rollout
spec:
  targetService:
    name: reviews
    apiVersion: v1
    baseline: reviews-v2
    candidate: reviews-v3
  trafficControl:
    strategy: check_and_increment
    interval: 30s
    trafficStepSize: 25
    maxIterations: 4
    maxTrafficPercentage: 80
  analysis:
    analyticsService: "http://iter8-analytics.iter8:8080"
    successCriteria:
      - metricName: iter8_latency
        toleranceType: threshold
        tolerance: 0.2
        sampleSize: 5
```
Note that step size and max iterations do not match what we have in the tutorial instructions, namely, 20 and 8, respectively.
